det_path: "mounting_023/mounting_023_det.txt"
mp4_path: "mounting_023/mounting_023.mp4"
trk_path: "mounting_023/mounting_023_trk.txt"
drink_iou : 0.0005
eat_iou : 0.0005
L_per_frame: 0.01
gram_per_frame: 0.1
kg_per_squaremeter: 1100
move_length_to_kcal: 0.00004437
m_per_pixel: 0.005