det_path: "../mounting_001/mounting_001_det.txt"
mp4_path: "../mounting_001/mounting_001.mp4"
trk_path: "../mounting_001/mounting_001_trk.txt"

drink_iou : 0.05
eat_iou : 0.05
L_per_frame: 0.01
gram_per_frame: 0.1